### ISSUE TITLE
Issue Building...

### ISSUE THREAD

**Issue by rtotheb2000** [hydeik/mxpfit#1]
Hi,

trying to build on ubuntu 18.04 with boost, fftw3 and eigen3 installed. `make` only tests, results in message

```
/home/somename/Documents/github/mxpfit/test/fftw3/shared_plan.cpp:2:10: fatal error: catch/catch.hpp: No such file or directory
 #include <catch/catch.hpp>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
test/fftw3/CMakeFiles/test_fftw3_shared_plan.dir/build.make:62: recipe for target 'test/fftw3/CMakeFiles/test_fftw3_shared_plan.dir/shared_plan.cpp.o' failed
make[2]: *** [test/fftw3/CMakeFiles/test_fftw3_shared_plan.dir/shared_plan.cpp.o] Error 1
CMakeFiles/Makefile2:106: recipe for target 'test/fftw3/CMakeFiles/test_fftw3_shared_plan.dir/all' failed
make[1]: *** [test/fftw3/CMakeFiles/test_fftw3_shared_plan.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

I used `cmake version 3.10.2` and  `gcc version 7.3.0` on Ubuntu 18.04.

`sudo apt-get install libfftw3-3` installs `version 3.3.7-1`

`sudo apt install libeigen3-dev` installs `version 3.3.4-4`

More issues appear, when building examples...

Can anyone help?

**Comment by hydeik** [comment]
Thank you for the report.

The problem is that the incorrect directory structures under the `test` directory.
This is fixed in the latest commit.

Please try it again.

**Comment by rtotheb2000** [comment]
Now, building throws

```
test/fftw3/CMakeFiles/test_fftw3_shared_plan.dir/build.make:62: recipe for target 'test/fftw3/CMakeFiles/test_fftw3_shared_plan.dir/shared_plan.cpp.o' failed
make[2]: *** [test/fftw3/CMakeFiles/test_fftw3_shared_plan.dir/shared_plan.cpp.o] Error 1
CMakeFiles/Makefile2:106: recipe for target 'test/fftw3/CMakeFiles/test_fftw3_shared_plan.dir/all' failed
make[1]: *** [test/fftw3/CMakeFiles/test_fftw3_shared_plan.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by hydeik** [comment]
I can't find the origin of errors only from this message.
Are there any other messages from compiler or linker?

Please also check whether FFTW3 library is detected properly.
What are the entries of `FFTW3_INCLUDE_DIR` and `FFTW3_LIBRARY` says in your `CMakeCache.txt` which is generated by cmake?

**Comment by hydeik** [comment]
You may also need to install `libfftw3-dev` package, which contains header files required for build.

**Comment by rtotheb2000** [comment]
`libfftw3-dev/bionic,now 3.3.7-1 amd64 [installed]
`

`ccmake` returns...

```
 FFTW3_INCLUDE_DIR                /usr/include                                                                                                                                                                    
 FFTW3_LIBRARY                    /usr/lib/x86_64-linux-gnu/libfftw3.so
```

example out of the very long error message list...

```
/home/somename/Documents/github/mxpfit/include/fftw3/shared_plan.hpp:174:41: error: ‘lock’ was not declared in this scope
             std::lock_guard<std::mutex> lock(fftw_plan_mutex<real_type>::m);   \
                                         ^
```

**Comment by hydeik** [comment]
Thanks. 

This error is due to the missing header file (clang works, though).
Insert  `#include <mutex>` in `include/fftw3/shared_plan.hpp` will solve the problem.

I just made a commit to fix this.

**Comment by rtotheb2000** [comment]
Now it works, thanks a lot.
